name: 'GitHub Recent Commits Authors'
description: 'Get Get GitHub Recent Commits Authors'
author: Aidar Gatin
branding:
  icon: 'users'
  color: 'purple'

inputs:
  github_repository: 
    description: 'GitHub Repository'
    required: false
    default: ${{ github.repository }}

  github_repository_branch: 
    description: 'GitHub Repository Branch'
    required: false
    default: 'HEAD'

  github_token: 
    description: 'GitHub Token'
    required: false
    default: ''

  days_before:
    description: 'Days before now'
    required: false
    default: '30'
  
  unique:
    description: 'Sort out Unique authors emails'
    required: false
    default: 'true'

  output_format:
    description: 'Output format'
    required: false
    default: 'json'
 
outputs:
  emails: 
    description: 'The emails list'
runs:
  using: 'node16'
  main: 'index.js'